// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/ddl.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateReq struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Fields               []*Field `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{0}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *CreateReq) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type CreateResp struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResp) Reset()         { *m = CreateResp{} }
func (m *CreateResp) String() string { return proto.CompactTextString(m) }
func (*CreateResp) ProtoMessage()    {}
func (*CreateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{1}
}

func (m *CreateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResp.Unmarshal(m, b)
}
func (m *CreateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResp.Marshal(b, m, deterministic)
}
func (m *CreateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResp.Merge(m, src)
}
func (m *CreateResp) XXX_Size() int {
	return xxx_messageInfo_CreateResp.Size(m)
}
func (m *CreateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResp proto.InternalMessageInfo

func (m *CreateResp) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

type AddReq struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Fields               []*Field `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReq) Reset()         { *m = AddReq{} }
func (m *AddReq) String() string { return proto.CompactTextString(m) }
func (*AddReq) ProtoMessage()    {}
func (*AddReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{2}
}

func (m *AddReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReq.Unmarshal(m, b)
}
func (m *AddReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReq.Marshal(b, m, deterministic)
}
func (m *AddReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReq.Merge(m, src)
}
func (m *AddReq) XXX_Size() int {
	return xxx_messageInfo_AddReq.Size(m)
}
func (m *AddReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddReq proto.InternalMessageInfo

func (m *AddReq) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *AddReq) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type AddResp struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResp) Reset()         { *m = AddResp{} }
func (m *AddResp) String() string { return proto.CompactTextString(m) }
func (*AddResp) ProtoMessage()    {}
func (*AddResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{3}
}

func (m *AddResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResp.Unmarshal(m, b)
}
func (m *AddResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResp.Marshal(b, m, deterministic)
}
func (m *AddResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResp.Merge(m, src)
}
func (m *AddResp) XXX_Size() int {
	return xxx_messageInfo_AddResp.Size(m)
}
func (m *AddResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddResp proto.InternalMessageInfo

func (m *AddResp) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

type ModifyReq struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Fields               []*Field `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyReq) Reset()         { *m = ModifyReq{} }
func (m *ModifyReq) String() string { return proto.CompactTextString(m) }
func (*ModifyReq) ProtoMessage()    {}
func (*ModifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{4}
}

func (m *ModifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyReq.Unmarshal(m, b)
}
func (m *ModifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyReq.Marshal(b, m, deterministic)
}
func (m *ModifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyReq.Merge(m, src)
}
func (m *ModifyReq) XXX_Size() int {
	return xxx_messageInfo_ModifyReq.Size(m)
}
func (m *ModifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyReq proto.InternalMessageInfo

func (m *ModifyReq) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *ModifyReq) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ModifyResp struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyResp) Reset()         { *m = ModifyResp{} }
func (m *ModifyResp) String() string { return proto.CompactTextString(m) }
func (*ModifyResp) ProtoMessage()    {}
func (*ModifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{5}
}

func (m *ModifyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyResp.Unmarshal(m, b)
}
func (m *ModifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyResp.Marshal(b, m, deterministic)
}
func (m *ModifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyResp.Merge(m, src)
}
func (m *ModifyResp) XXX_Size() int {
	return xxx_messageInfo_ModifyResp.Size(m)
}
func (m *ModifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyResp proto.InternalMessageInfo

func (m *ModifyResp) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

type Field struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Max                  int64    `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Comment              string   `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	NotNull              bool     `protobuf:"varint,5,opt,name=notNull,proto3" json:"notNull,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{6}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Field) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Field) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *Field) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Field) GetNotNull() bool {
	if m != nil {
		return m.NotNull
	}
	return false
}

type IndexesReq struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Option               string   `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	Titles               []string `protobuf:"bytes,3,rep,name=titles,proto3" json:"titles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexesReq) Reset()         { *m = IndexesReq{} }
func (m *IndexesReq) String() string { return proto.CompactTextString(m) }
func (*IndexesReq) ProtoMessage()    {}
func (*IndexesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{7}
}

func (m *IndexesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexesReq.Unmarshal(m, b)
}
func (m *IndexesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexesReq.Marshal(b, m, deterministic)
}
func (m *IndexesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexesReq.Merge(m, src)
}
func (m *IndexesReq) XXX_Size() int {
	return xxx_messageInfo_IndexesReq.Size(m)
}
func (m *IndexesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexesReq.DiscardUnknown(m)
}

var xxx_messageInfo_IndexesReq proto.InternalMessageInfo

func (m *IndexesReq) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *IndexesReq) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

func (m *IndexesReq) GetTitles() []string {
	if m != nil {
		return m.Titles
	}
	return nil
}

type IndexesResp struct {
	IndexName            string   `protobuf:"bytes,1,opt,name=indexName,proto3" json:"indexName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexesResp) Reset()         { *m = IndexesResp{} }
func (m *IndexesResp) String() string { return proto.CompactTextString(m) }
func (*IndexesResp) ProtoMessage()    {}
func (*IndexesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{8}
}

func (m *IndexesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexesResp.Unmarshal(m, b)
}
func (m *IndexesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexesResp.Marshal(b, m, deterministic)
}
func (m *IndexesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexesResp.Merge(m, src)
}
func (m *IndexesResp) XXX_Size() int {
	return xxx_messageInfo_IndexesResp.Size(m)
}
func (m *IndexesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexesResp.DiscardUnknown(m)
}

var xxx_messageInfo_IndexesResp proto.InternalMessageInfo

func (m *IndexesResp) GetIndexName() string {
	if m != nil {
		return m.IndexName
	}
	return ""
}

type DropIndexesReq struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	IndexName            []string `protobuf:"bytes,2,rep,name=indexName,proto3" json:"indexName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropIndexesReq) Reset()         { *m = DropIndexesReq{} }
func (m *DropIndexesReq) String() string { return proto.CompactTextString(m) }
func (*DropIndexesReq) ProtoMessage()    {}
func (*DropIndexesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{9}
}

func (m *DropIndexesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropIndexesReq.Unmarshal(m, b)
}
func (m *DropIndexesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropIndexesReq.Marshal(b, m, deterministic)
}
func (m *DropIndexesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropIndexesReq.Merge(m, src)
}
func (m *DropIndexesReq) XXX_Size() int {
	return xxx_messageInfo_DropIndexesReq.Size(m)
}
func (m *DropIndexesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DropIndexesReq.DiscardUnknown(m)
}

var xxx_messageInfo_DropIndexesReq proto.InternalMessageInfo

func (m *DropIndexesReq) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *DropIndexesReq) GetIndexName() []string {
	if m != nil {
		return m.IndexName
	}
	return nil
}

type DropIndexesResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropIndexesResp) Reset()         { *m = DropIndexesResp{} }
func (m *DropIndexesResp) String() string { return proto.CompactTextString(m) }
func (*DropIndexesResp) ProtoMessage()    {}
func (*DropIndexesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{10}
}

func (m *DropIndexesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropIndexesResp.Unmarshal(m, b)
}
func (m *DropIndexesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropIndexesResp.Marshal(b, m, deterministic)
}
func (m *DropIndexesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropIndexesResp.Merge(m, src)
}
func (m *DropIndexesResp) XXX_Size() int {
	return xxx_messageInfo_DropIndexesResp.Size(m)
}
func (m *DropIndexesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DropIndexesResp.DiscardUnknown(m)
}

var xxx_messageInfo_DropIndexesResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateReq)(nil), "proto.CreateReq")
	proto.RegisterType((*CreateResp)(nil), "proto.CreateResp")
	proto.RegisterType((*AddReq)(nil), "proto.AddReq")
	proto.RegisterType((*AddResp)(nil), "proto.AddResp")
	proto.RegisterType((*ModifyReq)(nil), "proto.ModifyReq")
	proto.RegisterType((*ModifyResp)(nil), "proto.ModifyResp")
	proto.RegisterType((*Field)(nil), "proto.Field")
	proto.RegisterType((*IndexesReq)(nil), "proto.IndexesReq")
	proto.RegisterType((*IndexesResp)(nil), "proto.IndexesResp")
	proto.RegisterType((*DropIndexesReq)(nil), "proto.DropIndexesReq")
	proto.RegisterType((*DropIndexesResp)(nil), "proto.DropIndexesResp")
}

func init() { proto.RegisterFile("api/proto/ddl.proto", fileDescriptor_c9bd5749e671052d) }

var fileDescriptor_c9bd5749e671052d = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcf, 0x8b, 0xda, 0x40,
	0x14, 0xc7, 0x89, 0x31, 0xb1, 0x79, 0xb6, 0x56, 0x5f, 0x5b, 0x09, 0xa1, 0x87, 0x10, 0x84, 0x86,
	0x96, 0x6a, 0xb1, 0xd7, 0x5e, 0xa4, 0x52, 0x28, 0x58, 0x85, 0xf4, 0xd6, 0x5b, 0x74, 0x46, 0x08,
	0x24, 0x99, 0x69, 0x66, 0xda, 0xd5, 0xdb, 0xfe, 0xe9, 0x4b, 0x26, 0x93, 0x18, 0x65, 0x59, 0xf7,
	0xe0, 0x29, 0xf3, 0xfd, 0xbe, 0xc9, 0xe7, 0xfd, 0x98, 0x07, 0x6f, 0x62, 0x9e, 0xcc, 0x78, 0xc1,
	0x24, 0x9b, 0x11, 0x92, 0x4e, 0xd5, 0x09, 0x2d, 0xf5, 0x09, 0x36, 0xe0, 0x7c, 0x2f, 0x68, 0x2c,
	0x69, 0x44, 0xff, 0xe2, 0x7b, 0x70, 0x64, 0xbc, 0x4d, 0xe9, 0x3a, 0xce, 0xa8, 0x6b, 0xf8, 0x46,
	0xe8, 0x44, 0x27, 0x03, 0x27, 0x60, 0xef, 0x13, 0x9a, 0x12, 0xe1, 0x9a, 0xbe, 0x19, 0xf6, 0xe7,
	0x2f, 0x2b, 0xd2, 0xf4, 0x47, 0x69, 0x46, 0x3a, 0x16, 0x7c, 0x04, 0xa8, 0x81, 0x82, 0x3f, 0x4d,
	0x0c, 0x56, 0x60, 0x2f, 0x08, 0xb9, 0x55, 0xe6, 0x0f, 0xd0, 0x53, 0xb4, 0xab, 0x69, 0x37, 0xe0,
	0xfc, 0x62, 0x24, 0xd9, 0x1f, 0x6f, 0xd8, 0x73, 0x0d, 0xbc, 0x9a, 0xfc, 0x0e, 0x2c, 0xf5, 0x33,
	0xbe, 0x05, 0x4b, 0x26, 0x32, 0xad, 0xaf, 0x54, 0x02, 0x11, 0xba, 0xf2, 0xc8, 0xa9, 0xdb, 0x51,
	0xa6, 0x3a, 0xe3, 0x10, 0xcc, 0x2c, 0x3e, 0xb8, 0xa6, 0x6f, 0x84, 0x66, 0x54, 0x1e, 0xd1, 0x85,
	0xde, 0x8e, 0x65, 0x19, 0xcd, 0xa5, 0xdb, 0x55, 0x17, 0x6b, 0x59, 0x46, 0x72, 0x26, 0xd7, 0xff,
	0xd2, 0xd4, 0xb5, 0x7c, 0x23, 0x7c, 0x11, 0xd5, 0x32, 0xf8, 0x03, 0xf0, 0x33, 0x27, 0xf4, 0x40,
	0xc5, 0xf5, 0xb6, 0xc7, 0x60, 0x33, 0x2e, 0x13, 0x96, 0xeb, 0x3a, 0xb4, 0x2a, 0x7d, 0x55, 0x66,
	0x35, 0x0e, 0x27, 0xd2, 0x2a, 0xf8, 0x04, 0xfd, 0x86, 0x5d, 0x4d, 0x20, 0x29, 0x65, 0x1b, 0xde,
	0x18, 0xc1, 0x0a, 0x06, 0xcb, 0x82, 0xf1, 0x67, 0x17, 0x73, 0x46, 0xeb, 0xa8, 0xbc, 0x2d, 0xda,
	0x08, 0x5e, 0x9f, 0xd1, 0x04, 0x9f, 0xdf, 0x77, 0x00, 0x96, 0xcb, 0xd5, 0x6f, 0x5a, 0xfc, 0x4f,
	0x76, 0x14, 0x3f, 0x83, 0x5d, 0x6d, 0x24, 0x0e, 0xf5, 0xeb, 0x35, 0x1b, 0xef, 0x8d, 0x2e, 0x1c,
	0xc1, 0x71, 0x02, 0xe6, 0x82, 0x10, 0x7c, 0xa5, 0x23, 0xd5, 0x82, 0x7a, 0x83, 0xb6, 0x14, 0xbc,
	0x84, 0x56, 0x4f, 0xde, 0x40, 0x9b, 0x95, 0x6a, 0xa0, 0xad, 0x9d, 0xf8, 0x02, 0x3d, 0x5d, 0x21,
	0xd6, 0xd1, 0x53, 0xff, 0x1e, 0x5e, 0x5a, 0x82, 0xe3, 0x37, 0xe8, 0xb7, 0xfa, 0xc2, 0x77, 0xfa,
	0xca, 0xf9, 0xe4, 0xbc, 0xf1, 0x63, 0xb6, 0xe0, 0x5b, 0x5b, 0xd9, 0x5f, 0x1f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x62, 0xd0, 0x91, 0xda, 0xfb, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DDLServiceClient is the client API for DDLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DDLServiceClient interface {
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error)
	Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error)
	Modify(ctx context.Context, in *ModifyReq, opts ...grpc.CallOption) (*ModifyResp, error)
	Indexes(ctx context.Context, in *IndexesReq, opts ...grpc.CallOption) (*IndexesResp, error)
	DropIndexes(ctx context.Context, in *DropIndexesReq, opts ...grpc.CallOption) (*DropIndexesResp, error)
}

type dDLServiceClient struct {
	cc *grpc.ClientConn
}

func NewDDLServiceClient(cc *grpc.ClientConn) DDLServiceClient {
	return &dDLServiceClient{cc}
}

func (c *dDLServiceClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error) {
	out := new(CreateResp)
	err := c.cc.Invoke(ctx, "/proto.DDLService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dDLServiceClient) Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error) {
	out := new(AddResp)
	err := c.cc.Invoke(ctx, "/proto.DDLService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dDLServiceClient) Modify(ctx context.Context, in *ModifyReq, opts ...grpc.CallOption) (*ModifyResp, error) {
	out := new(ModifyResp)
	err := c.cc.Invoke(ctx, "/proto.DDLService/Modify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dDLServiceClient) Indexes(ctx context.Context, in *IndexesReq, opts ...grpc.CallOption) (*IndexesResp, error) {
	out := new(IndexesResp)
	err := c.cc.Invoke(ctx, "/proto.DDLService/Indexes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dDLServiceClient) DropIndexes(ctx context.Context, in *DropIndexesReq, opts ...grpc.CallOption) (*DropIndexesResp, error) {
	out := new(DropIndexesResp)
	err := c.cc.Invoke(ctx, "/proto.DDLService/DropIndexes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DDLServiceServer is the server API for DDLService service.
type DDLServiceServer interface {
	Create(context.Context, *CreateReq) (*CreateResp, error)
	Add(context.Context, *AddReq) (*AddResp, error)
	Modify(context.Context, *ModifyReq) (*ModifyResp, error)
	Indexes(context.Context, *IndexesReq) (*IndexesResp, error)
	DropIndexes(context.Context, *DropIndexesReq) (*DropIndexesResp, error)
}

// UnimplementedDDLServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDDLServiceServer struct {
}

func (*UnimplementedDDLServiceServer) Create(ctx context.Context, req *CreateReq) (*CreateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedDDLServiceServer) Add(ctx context.Context, req *AddReq) (*AddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedDDLServiceServer) Modify(ctx context.Context, req *ModifyReq) (*ModifyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Modify not implemented")
}
func (*UnimplementedDDLServiceServer) Indexes(ctx context.Context, req *IndexesReq) (*IndexesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Indexes not implemented")
}
func (*UnimplementedDDLServiceServer) DropIndexes(ctx context.Context, req *DropIndexesReq) (*DropIndexesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropIndexes not implemented")
}

func RegisterDDLServiceServer(s *grpc.Server, srv DDLServiceServer) {
	s.RegisterService(&_DDLService_serviceDesc, srv)
}

func _DDLService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DDLServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DDLService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DDLServiceServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DDLService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DDLServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DDLService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DDLServiceServer).Add(ctx, req.(*AddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DDLService_Modify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DDLServiceServer).Modify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DDLService/Modify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DDLServiceServer).Modify(ctx, req.(*ModifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DDLService_Indexes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DDLServiceServer).Indexes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DDLService/Indexes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DDLServiceServer).Indexes(ctx, req.(*IndexesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DDLService_DropIndexes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropIndexesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DDLServiceServer).DropIndexes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DDLService/DropIndexes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DDLServiceServer).DropIndexes(ctx, req.(*DropIndexesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DDLService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DDLService",
	HandlerType: (*DDLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DDLService_Create_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _DDLService_Add_Handler,
		},
		{
			MethodName: "Modify",
			Handler:    _DDLService_Modify_Handler,
		},
		{
			MethodName: "Indexes",
			Handler:    _DDLService_Indexes_Handler,
		},
		{
			MethodName: "DropIndexes",
			Handler:    _DDLService_DropIndexes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/ddl.proto",
}
