// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/ddl.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExecuteReq struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Option               string   `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	Fields               []*Field `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteReq) Reset()         { *m = ExecuteReq{} }
func (m *ExecuteReq) String() string { return proto.CompactTextString(m) }
func (*ExecuteReq) ProtoMessage()    {}
func (*ExecuteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{0}
}

func (m *ExecuteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteReq.Unmarshal(m, b)
}
func (m *ExecuteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteReq.Marshal(b, m, deterministic)
}
func (m *ExecuteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteReq.Merge(m, src)
}
func (m *ExecuteReq) XXX_Size() int {
	return xxx_messageInfo_ExecuteReq.Size(m)
}
func (m *ExecuteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteReq proto.InternalMessageInfo

func (m *ExecuteReq) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *ExecuteReq) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

func (m *ExecuteReq) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ExecuteResp struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteResp) Reset()         { *m = ExecuteResp{} }
func (m *ExecuteResp) String() string { return proto.CompactTextString(m) }
func (*ExecuteResp) ProtoMessage()    {}
func (*ExecuteResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{1}
}

func (m *ExecuteResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteResp.Unmarshal(m, b)
}
func (m *ExecuteResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteResp.Marshal(b, m, deterministic)
}
func (m *ExecuteResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteResp.Merge(m, src)
}
func (m *ExecuteResp) XXX_Size() int {
	return xxx_messageInfo_ExecuteResp.Size(m)
}
func (m *ExecuteResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteResp.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteResp proto.InternalMessageInfo

func (m *ExecuteResp) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

type Field struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Max                  int64    `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Comment              string   `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	NotNull              bool     `protobuf:"varint,5,opt,name=notNull,proto3" json:"notNull,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{2}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Field) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Field) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *Field) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Field) GetNotNull() bool {
	if m != nil {
		return m.NotNull
	}
	return false
}

type IndexesReq struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Option               string   `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	Titles               []string `protobuf:"bytes,3,rep,name=titles,proto3" json:"titles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexesReq) Reset()         { *m = IndexesReq{} }
func (m *IndexesReq) String() string { return proto.CompactTextString(m) }
func (*IndexesReq) ProtoMessage()    {}
func (*IndexesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{3}
}

func (m *IndexesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexesReq.Unmarshal(m, b)
}
func (m *IndexesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexesReq.Marshal(b, m, deterministic)
}
func (m *IndexesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexesReq.Merge(m, src)
}
func (m *IndexesReq) XXX_Size() int {
	return xxx_messageInfo_IndexesReq.Size(m)
}
func (m *IndexesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexesReq.DiscardUnknown(m)
}

var xxx_messageInfo_IndexesReq proto.InternalMessageInfo

func (m *IndexesReq) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *IndexesReq) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

func (m *IndexesReq) GetTitles() []string {
	if m != nil {
		return m.Titles
	}
	return nil
}

type IndexesResp struct {
	IndexName            string   `protobuf:"bytes,1,opt,name=indexName,proto3" json:"indexName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexesResp) Reset()         { *m = IndexesResp{} }
func (m *IndexesResp) String() string { return proto.CompactTextString(m) }
func (*IndexesResp) ProtoMessage()    {}
func (*IndexesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{4}
}

func (m *IndexesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexesResp.Unmarshal(m, b)
}
func (m *IndexesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexesResp.Marshal(b, m, deterministic)
}
func (m *IndexesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexesResp.Merge(m, src)
}
func (m *IndexesResp) XXX_Size() int {
	return xxx_messageInfo_IndexesResp.Size(m)
}
func (m *IndexesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexesResp.DiscardUnknown(m)
}

var xxx_messageInfo_IndexesResp proto.InternalMessageInfo

func (m *IndexesResp) GetIndexName() string {
	if m != nil {
		return m.IndexName
	}
	return ""
}

type DropIndexesReq struct {
	TableName            string   `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	IndexName            []string `protobuf:"bytes,2,rep,name=indexName,proto3" json:"indexName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropIndexesReq) Reset()         { *m = DropIndexesReq{} }
func (m *DropIndexesReq) String() string { return proto.CompactTextString(m) }
func (*DropIndexesReq) ProtoMessage()    {}
func (*DropIndexesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{5}
}

func (m *DropIndexesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropIndexesReq.Unmarshal(m, b)
}
func (m *DropIndexesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropIndexesReq.Marshal(b, m, deterministic)
}
func (m *DropIndexesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropIndexesReq.Merge(m, src)
}
func (m *DropIndexesReq) XXX_Size() int {
	return xxx_messageInfo_DropIndexesReq.Size(m)
}
func (m *DropIndexesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DropIndexesReq.DiscardUnknown(m)
}

var xxx_messageInfo_DropIndexesReq proto.InternalMessageInfo

func (m *DropIndexesReq) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *DropIndexesReq) GetIndexName() []string {
	if m != nil {
		return m.IndexName
	}
	return nil
}

type DropIndexesResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropIndexesResp) Reset()         { *m = DropIndexesResp{} }
func (m *DropIndexesResp) String() string { return proto.CompactTextString(m) }
func (*DropIndexesResp) ProtoMessage()    {}
func (*DropIndexesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9bd5749e671052d, []int{6}
}

func (m *DropIndexesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropIndexesResp.Unmarshal(m, b)
}
func (m *DropIndexesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropIndexesResp.Marshal(b, m, deterministic)
}
func (m *DropIndexesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropIndexesResp.Merge(m, src)
}
func (m *DropIndexesResp) XXX_Size() int {
	return xxx_messageInfo_DropIndexesResp.Size(m)
}
func (m *DropIndexesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DropIndexesResp.DiscardUnknown(m)
}

var xxx_messageInfo_DropIndexesResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ExecuteReq)(nil), "proto.ExecuteReq")
	proto.RegisterType((*ExecuteResp)(nil), "proto.ExecuteResp")
	proto.RegisterType((*Field)(nil), "proto.Field")
	proto.RegisterType((*IndexesReq)(nil), "proto.IndexesReq")
	proto.RegisterType((*IndexesResp)(nil), "proto.IndexesResp")
	proto.RegisterType((*DropIndexesReq)(nil), "proto.DropIndexesReq")
	proto.RegisterType((*DropIndexesResp)(nil), "proto.DropIndexesResp")
}

func init() { proto.RegisterFile("api/proto/ddl.proto", fileDescriptor_c9bd5749e671052d) }

var fileDescriptor_c9bd5749e671052d = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x25, 0x4d, 0x93, 0xda, 0xa9, 0xa8, 0x1d, 0xb5, 0x2c, 0xc5, 0x43, 0x08, 0x1e, 0x02, 0x42,
	0x2b, 0xf5, 0xea, 0xb1, 0x0a, 0x42, 0xe9, 0x21, 0xde, 0xbc, 0xa5, 0xcd, 0x88, 0x81, 0x24, 0xbb,
	0x76, 0xb7, 0x5a, 0x7f, 0xca, 0x6f, 0x94, 0xdd, 0x6c, 0xd3, 0x54, 0x44, 0xc4, 0x53, 0xe6, 0xbd,
	0x99, 0x79, 0xf3, 0x76, 0x26, 0x70, 0x9a, 0x88, 0x6c, 0x2c, 0x56, 0x5c, 0xf1, 0x71, 0x9a, 0xe6,
	0x23, 0x13, 0xa1, 0x67, 0x3e, 0xe1, 0x0b, 0xc0, 0xdd, 0x86, 0x96, 0x6b, 0x45, 0x31, 0xbd, 0xe2,
	0x05, 0x74, 0x55, 0xb2, 0xc8, 0x69, 0x9e, 0x14, 0xc4, 0x9c, 0xc0, 0x89, 0xba, 0xf1, 0x8e, 0xc0,
	0x01, 0xf8, 0x5c, 0xa8, 0x8c, 0x97, 0xac, 0x65, 0x52, 0x16, 0xe1, 0x25, 0xf8, 0xcf, 0x19, 0xe5,
	0xa9, 0x64, 0x6e, 0xe0, 0x46, 0xbd, 0xc9, 0x61, 0x35, 0x62, 0x74, 0xaf, 0xc9, 0xd8, 0xe6, 0xc2,
	0x2b, 0xe8, 0xd5, 0x93, 0xa4, 0xf8, 0x7d, 0x54, 0xf8, 0x0e, 0x9e, 0xe9, 0xc6, 0x33, 0xf0, 0x54,
	0xa6, 0xf2, 0x6d, 0x49, 0x05, 0x10, 0xa1, 0xad, 0x3e, 0x04, 0x59, 0x1f, 0x26, 0xc6, 0x13, 0x70,
	0x8b, 0x64, 0xc3, 0xdc, 0xc0, 0x89, 0xdc, 0x58, 0x87, 0xc8, 0xa0, 0xb3, 0xe4, 0x45, 0x41, 0xa5,
	0x62, 0x6d, 0x53, 0xb8, 0x85, 0x3a, 0x53, 0x72, 0x35, 0x5f, 0xe7, 0x39, 0xf3, 0x02, 0x27, 0x3a,
	0x88, 0xb7, 0x30, 0x7c, 0x02, 0x78, 0x28, 0x53, 0xda, 0x90, 0xfc, 0xff, 0x3e, 0x06, 0xe0, 0x1b,
	0x9b, 0xd5, 0x3e, 0xba, 0xb1, 0x45, 0x7a, 0x03, 0xb5, 0x76, 0xb5, 0x81, 0x4c, 0xc3, 0xa6, 0x78,
	0x4d, 0x84, 0x33, 0x38, 0x9a, 0xae, 0xb8, 0xf8, 0xb3, 0x99, 0x3d, 0xb5, 0x96, 0x99, 0xdb, 0x50,
	0xeb, 0xc3, 0xf1, 0x9e, 0x9a, 0x14, 0x93, 0x4f, 0x07, 0x60, 0x3a, 0x9d, 0x3d, 0xd2, 0xea, 0x2d,
	0x5b, 0x12, 0x5e, 0x43, 0xc7, 0x9e, 0x07, 0xfb, 0xf6, 0x7e, 0xbb, 0x1f, 0x63, 0x88, 0xdf, 0x29,
	0x29, 0x74, 0x87, 0xd5, 0xab, 0x3b, 0x76, 0x6e, 0xeb, 0x8e, 0xe6, 0x8b, 0x6f, 0xa1, 0xd7, 0x70,
	0x81, 0xe7, 0xb6, 0x64, 0xff, 0x9d, 0xc3, 0xc1, 0x4f, 0xb4, 0x14, 0x0b, 0xdf, 0xd0, 0x37, 0x5f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x02, 0x66, 0x94, 0xcf, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DDLServiceClient is the client API for DDLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DDLServiceClient interface {
	Execute(ctx context.Context, in *ExecuteReq, opts ...grpc.CallOption) (*ExecuteResp, error)
	Indexes(ctx context.Context, in *IndexesReq, opts ...grpc.CallOption) (*IndexesResp, error)
	DropIndexes(ctx context.Context, in *DropIndexesReq, opts ...grpc.CallOption) (*DropIndexesResp, error)
}

type dDLServiceClient struct {
	cc *grpc.ClientConn
}

func NewDDLServiceClient(cc *grpc.ClientConn) DDLServiceClient {
	return &dDLServiceClient{cc}
}

func (c *dDLServiceClient) Execute(ctx context.Context, in *ExecuteReq, opts ...grpc.CallOption) (*ExecuteResp, error) {
	out := new(ExecuteResp)
	err := c.cc.Invoke(ctx, "/proto.DDLService/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dDLServiceClient) Indexes(ctx context.Context, in *IndexesReq, opts ...grpc.CallOption) (*IndexesResp, error) {
	out := new(IndexesResp)
	err := c.cc.Invoke(ctx, "/proto.DDLService/Indexes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dDLServiceClient) DropIndexes(ctx context.Context, in *DropIndexesReq, opts ...grpc.CallOption) (*DropIndexesResp, error) {
	out := new(DropIndexesResp)
	err := c.cc.Invoke(ctx, "/proto.DDLService/DropIndexes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DDLServiceServer is the server API for DDLService service.
type DDLServiceServer interface {
	Execute(context.Context, *ExecuteReq) (*ExecuteResp, error)
	Indexes(context.Context, *IndexesReq) (*IndexesResp, error)
	DropIndexes(context.Context, *DropIndexesReq) (*DropIndexesResp, error)
}

// UnimplementedDDLServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDDLServiceServer struct {
}

func (*UnimplementedDDLServiceServer) Execute(ctx context.Context, req *ExecuteReq) (*ExecuteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (*UnimplementedDDLServiceServer) Indexes(ctx context.Context, req *IndexesReq) (*IndexesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Indexes not implemented")
}
func (*UnimplementedDDLServiceServer) DropIndexes(ctx context.Context, req *DropIndexesReq) (*DropIndexesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropIndexes not implemented")
}

func RegisterDDLServiceServer(s *grpc.Server, srv DDLServiceServer) {
	s.RegisterService(&_DDLService_serviceDesc, srv)
}

func _DDLService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DDLServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DDLService/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DDLServiceServer).Execute(ctx, req.(*ExecuteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DDLService_Indexes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DDLServiceServer).Indexes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DDLService/Indexes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DDLServiceServer).Indexes(ctx, req.(*IndexesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DDLService_DropIndexes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropIndexesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DDLServiceServer).DropIndexes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DDLService/DropIndexes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DDLServiceServer).DropIndexes(ctx, req.(*DropIndexesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DDLService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DDLService",
	HandlerType: (*DDLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _DDLService_Execute_Handler,
		},
		{
			MethodName: "Indexes",
			Handler:    _DDLService_Indexes_Handler,
		},
		{
			MethodName: "DropIndexes",
			Handler:    _DDLService_DropIndexes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/ddl.proto",
}
